services:
  web-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./envirotrack:/envirotrack
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  web-app-frontend:
    build: 
      context: ./frontend  
    ports:
      - "3000:3000"
    depends_on:
      - web-app 
    command: sh -c "npm start"