# Generated by Django 4.1.7 on 2023-10-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='humidity_percentage',
        ),
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='pressure_kpa',
        ),
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='pressure_mmhg',
        ),
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='temperature_celsius',
        ),
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure_kpa', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pressure_mmhg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_time', models.DateTimeField()),
                ('measurement_instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.measurementinstrument')),
            ],
            options={
                'verbose_name': 'Набор параметров',
                'verbose_name_plural': 'Наборы параметров',
            },
        ),
        migrations.AddField(
            model_name='enviromentalparameters',
            name='parameter_sets',
            field=models.ManyToManyField(to='backend.parameterset'),
        ),
    ]
