# Generated by Django 4.2.4 on 2023-08-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='responsible_persons',
            field=models.ManyToManyField(related_name='rooms', to='backend.responsible'),
        ),
    ]
