# Generated by Django 4.1.7 on 2023-10-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_enviromentalparameters_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='parameter_sets',
        ),
        migrations.AddField(
            model_name='enviromentalparameters',
            name='evening_parameter_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evening_parameters', to='backend.parameterset'),
        ),
        migrations.AddField(
            model_name='enviromentalparameters',
            name='morning_parameter_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morning_parameters', to='backend.parameterset'),
        ),
    ]
