# Generated by Django 4.1.7 on 2023-10-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_enviromentalparameters_parameter_sets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enviromentalparameters',
            old_name='evening_parameter_set',
            new_name='parameter_set',
        ),
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='morning_parameter_set',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='measurement_instrument',
        ),
    ]
