# Generated by Django 4.2.4 on 2023-09-01 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_responsible_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=50)),
                ('calibration_date', models.DateField()),
                ('calibration_interval', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='responsible',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
