# Generated by Django 4.2.4 on 2023-09-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_measurementinstrument_alter_responsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviromentalparameters',
            name='measurement_instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.measurementinstrument'),
        ),
    ]
