# Generated by Django 4.1.7 on 2023-10-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_evening_parameter_set_enviromentalparameters_parameter_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='parameter_set',
        ),
        migrations.AddField(
            model_name='enviromentalparameters',
            name='parameter_set',
            field=models.ManyToManyField(null=True, related_name='evening_parameters', to='backend.parameterset'),
        ),
    ]
