# Generated by Django 4.1.7 on 2023-10-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_enviromentalparameters_parameter_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='parameter_set',
        ),
        migrations.AddField(
            model_name='enviromentalparameters',
            name='parameter_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evening_parameters', to='backend.parameterset'),
        ),
    ]
