# Generated by Django 4.1.7 on 2023-09-19 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_enviromentalparameters_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviromentalparameters',
            options={'verbose_name': 'Параметры окружающей среды', 'verbose_name_plural': 'Параметры окружающей среды'},
        ),
        migrations.AlterModelOptions(
            name='measurementinstrument',
            options={'verbose_name': 'Средство измерения', 'verbose_name_plural': 'Средства измерения'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AlterModelOptions(
            name='responsible',
            options={'verbose_name': 'Ответственный', 'verbose_name_plural': 'Ответственные'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='calibration_date',
            field=models.DateField(verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='calibration_interval',
            field=models.PositiveIntegerField(verbose_name='Межповерочный интервал'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.profession', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='room',
            name='responsible_persons',
            field=models.ManyToManyField(related_name='rooms', to='backend.responsible', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, verbose_name='Номер помещения'),
        ),
    ]
