# Generated by Django 4.1.7 on 2023-10-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_enviromentalparameters_parameter_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='parameter_set',
        ),
        migrations.AddField(
            model_name='enviromentalparameters',
            name='parameter_sets',
            field=models.ManyToManyField(blank=True, related_name='environmental_parameters', to='backend.parameterset'),
        ),
    ]
